# data_path config for BUSI dataset
data_root: ../data/Hi-gMISnet_all_dataset/BUSI
train_folder: train_folder
val_folder: val_folder
test_folder: test_folder

results_path: ../results/BUSI/train

model_name: unetpp

training:
  batch_size:
    train: 8
    eval: 4
  num_classes: 2
  learning_rate: 0.0001
  num_epochs: 300
  early_stopping_patience: 5
