datasets:
  BUSI:
    data_root: ../data/Hi-gMISnet_all_dataset/BUSI
    train_folder: train_folder
    val_folder: val_folder
    test_folder: test_folder
  DynamicNuclear:
    data_root: ../data/dynamicnuclear
    train_folder: train
    val_folder:   val
    test_folder:  test

model_name: UNetConcat

training:
  batch_size:
    train: 1
    eval: 1
  num_classes: 2
  learning_rate: 0.0001
  num_epochs: 300
  early_stopping_patience: 5

testing:
  batch_size: 4
  num_classes: 2
